import { useEffect, useState } from "react";
import { Alert, Button, Empty, InputNumber, Modal, Table, Tag, Typography, message } from "antd";
import { FileExcelOutlined, PauseOutlined, PlayCircleOutlined, QrcodeOutlined, StopOutlined } from "@ant-design/icons";
import QRScanner from "../Sales/QRScanner";
import { correctQRInventoryAPI, createQRInventoryAPI, downloadQRInventoryReportAPI, getQRInventoryAPI, scanQRInventoryAPI, transitionQRInventoryAPI } from "../../api/qrInventory";
const { Text, Title } = Typography;
type Props = { open: boolean; onClose: () => void; sucursalId?: string; sucursalLabel?: string };

const InventoryQRModal = ({ open, onClose, sucursalId, sucursalLabel }: Props) => {
  const [inventory, setInventory] = useState<any>(null); const [loading, setLoading] = useState(false); const [scanner, setScanner] = useState(false);
  const load = async (quiet = false) => { if (!sucursalId) return; try { const data = await getQRInventoryAPI(sucursalId); setInventory(data.inventory); } catch { if (!quiet) message.error("No se pudo cargar el inventario"); } finally { if (!quiet) setLoading(false); } };
  useEffect(() => { if (!open) { setScanner(false); return; } setLoading(true); load(); }, [open, sucursalId]);
  useEffect(() => { if (!open || !inventory || inventory.status === "closed") return; const timer = window.setInterval(() => load(true), 1500); return () => window.clearInterval(timer); }, [open, inventory?._id, inventory?.version, inventory?.status, sucursalId]);
  const create = async () => { if (!sucursalId) return; try { const data = await createQRInventoryAPI(sucursalId); setInventory(data.inventory); message.success("Inventario iniciado"); } catch (e: any) { message.error(e?.response?.data?.message || "No se pudo iniciar"); } };
  const scan = async (item: any) => { try { const data = await scanQRInventoryAPI(inventory._id, item.qrPayload || item.qrCode); setInventory(data.inventory); } catch (e: any) { message.error(e?.response?.data?.message || "No se pudo guardar la lectura"); } };
  const correct = async (row: any, value: number | null) => { if (value === null) return; try { const data = await correctQRInventoryAPI(inventory._id, row._id, value); setInventory(data.inventory); } catch (e: any) { message.error(e?.response?.data?.message || "No se pudo corregir"); } };
  const transition = async (status: "open" | "paused" | "closed") => { try { const data = await transitionQRInventoryAPI(inventory._id, status); setInventory(data.inventory); setScanner(false); } catch (e: any) { message.error(e?.response?.data?.message || "No se pudo actualizar"); } };
  const editable = inventory?.status === "open";
  return <Modal open={open} onCancel={onClose} footer={null} width={1120} destroyOnClose title="Inventario QR por sucursal">
    {!sucursalId ? <Empty description="Selecciona una sucursal para iniciar el inventario QR." /> : !inventory ? <div style={{ textAlign: "center", padding: 36 }}><Title level={4}>No hay inventario activo</Title><Text type="secondary">El inventario pertenecerá solo a {sucursalLabel || "esta sucursal"}.</Text><br /><Button type="primary" loading={loading} onClick={create} style={{ marginTop: 18 }}>Iniciar inventario</Button></div> : <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>
      <Alert type={inventory.status === "closed" ? "info" : inventory.status === "paused" ? "warning" : "success"} showIcon message={<span>Estado: <b>{inventory.status === "open" ? "Abierto" : inventory.status === "paused" ? "Pausado" : "Cerrado"}</b> · Stock al iniciar: {new Date(inventory.startedAt).toLocaleString("es-BO")}</span>} description={inventory.status === "open" ? "Cada lectura se guarda y se sincroniza con otros dispositivos." : inventory.status === "paused" ? "El avance esta guardado. Reanuda para seguir contando." : "Este inventario es solo de lectura y no modifica stock."}/>
      <div style={{ display: "flex", justifyContent: "space-between", gap: 8, flexWrap: "wrap" }}><div><Tag color="blue">{sucursalLabel || "Sucursal"}</Tag><Tag>Filas: {inventory.rows?.length || 0}</Tag></div><div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>{editable && <Button icon={<QrcodeOutlined />} type="primary" onClick={() => setScanner(!scanner)}>{scanner ? "Ocultar escaner" : "Escanear"}</Button>}{inventory.status === "open" && <Button icon={<PauseOutlined />} onClick={() => transition("paused")}>Pausar</Button>}{inventory.status === "paused" && <Button icon={<PlayCircleOutlined />} onClick={() => transition("open")}>Reanudar</Button>}{inventory.status !== "closed" && <Button danger icon={<StopOutlined />} onClick={() => transition("closed")}>Cerrar inventario</Button>}{inventory.status === "closed" && <Button type="primary" onClick={create}>Nuevo inventario</Button>}<Button icon={<FileExcelOutlined />} onClick={() => downloadQRInventoryReportAPI(inventory._id)}>Reporte Excel</Button></div></div>
      {scanner && editable && <QRScanner onProductScanned={scan} onClose={() => setScanner(false)} sucursalId={sucursalId} appearance="simple" title="Escaner QR de inventario" description="Cada lectura se guarda y suma una unidad." successLabel="Unidad guardada" />}
      <Table rowKey="_id" dataSource={inventory.rows || []} pagination={{ pageSize: 10 }} scroll={{ x: "max-content" }} columns={[{ title: "Producto", render: (_: any, row: any) => <><b>{row.productName}</b><br /><Text type="secondary">{row.variantLabel}</Text></> }, { title: "Contado / Stock al iniciar", render: (_: any, row: any) => <b>{row.countedStock} / {row.initialStock}</b> }, { title: "Diferencia", render: (_: any, row: any) => { const d = row.countedStock - row.initialStock; return <Text style={{ color: d === 0 ? undefined : d > 0 ? "#237804" : "#cf1322" }}>{d > 0 ? `+${d}` : d}</Text>; } }, { title: "Ultima actualizacion", render: (_: any, row: any) => <><div>{new Date(row.lastModifiedAt).toLocaleTimeString("es-BO")}</div><Text type="secondary">{row.lastModifiedByName || "-"}</Text></> }, ...(editable ? [{ title: "Corregir", render: (_: any, row: any) => <InputNumber min={0} value={row.countedStock} onChange={(value) => correct(row, value)} /> }] : [])]} />
    </div>}
  </Modal>;
};
export default InventoryQRModal;
