export const COUNTRY_CODES = [
  { code: '+591', name: 'Bolivia', flag: 'BO' },
  { code: '+54', name: 'Argentina', flag: 'AR' },
  { code: '+55', name: 'Brasil', flag: 'BR' },
  { code: '+506', name: 'Costa Rica', flag: 'CR' },
  { code: '+53', name: 'Cuba', flag: 'CU' },
  { code: '+503', name: 'El Salvador', flag: 'SV' },
  { code: '+593', name: 'Ecuador', flag: 'EC' },
  { code: '+1', name: 'EE.UU.', flag: 'US' },
  { code: '+34', name: 'España', flag: 'ES' },
  { code: '+502', name: 'Guatemala', flag: 'GT' },
  { code: '+504', name: 'Honduras', flag: 'HN' },
  { code: '+52', name: 'México', flag: 'MX' },
  { code: '+505', name: 'Nicaragua', flag: 'NI' },
  { code: '+507', name: 'Panamá', flag: 'PA' },
  { code: '+51', name: 'Perú', flag: 'PE' },
  { code: '+56', name: 'Chile', flag: 'CL' },
  { code: '+57', name: 'Colombia', flag: 'CO' },
  { code: '+58', name: 'Venezuela', flag: 'VE' },
];
