export const DATE_TAGS = {
  LAST_7_DAYS: "LAST_7_DAYS",
  LAST_30_DAYS: "LAST_30_DAYS",
  LAST_90_DAYS: "LAST_90_DAYS",
  LAST_YEAR: "LAST_YEAR",
  CUSTOM: "CUSTOM",
  ALL_TIME: "ALL_TIME",
};

export const FLUX_TYPES = {
  GASTO: "GASTO",
  INGRESO: "INGRESO",
  INVERSION: "INVERSION",
};
