export const TIPO_PAGO = {
  TRANSFERENCIA_O_QR: "TRANSFERENCIA O QR",
  EFECTIVO: "EFECTIVO",
  PAGADO_AL_DUENO: "PAGADO AL DUEÑO",
};

export const ESTADO_PEDIDO = {
  EN_ESPERA: "EN ESPERA",
  POR_ENTREGAR: "POR ENTREGAR",
  ENTREGADO: "ENTREGADO",
};
